# Generated by Django 4.0.4 on 2022-11-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='mandeh',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
