# Generated by Django 4.0.4 on 2022-11-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_doctors_mandeh'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
