# Generated by Django 4.0.4 on 2022-11-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_doctors_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
